### ISSUE TITLE
Why the number of categories is 9?

### ISSUE THREAD

**Issue by mrsempress** [ymingxie/PARQ#3]
May I ask why the results of the experiment are only on the 9 categories of scannet, instead of the general 18 categories? Maybe because of limited reading, which previous work did you follow, or some concerns? Looking forward to your answer, thank you.

**Comment by ymingxie** [comment]
Thanks for the interest in our work!

We followed ODAM(https://arxiv.org/abs/2108.10165) and RayTran(https://arxiv.org/abs/2203.13296), in which they report the top-8 super-classes and group all the other classes together as 'other'. 

Note that the annotations used in our work are from [Scan2Cad](https://github.com/skanti/Scan2CAD) instead of ScanNet. ScanNet only provides axis-aligned bounding boxes (AABB), while oriented 3D boxes are needed in our work.

Generally, 18 classes are usually reported if using ScanNet annotation and only predicted AABB, and 9 classes are usually reported if using Scan2CAD annotations and predicted oriented boxes.

Thanks,
Yiming

**Comment by mrsempress** [comment]
Thanks for your answer. I will read the above paper carefully. And think about which tasks require axis-aligned bounding boxes and which tasks require oriented 3D boxes.
